### ISSUE TITLE
Files are not consistently uploaded.

### ISSUE THREAD

**Issue by usepowershell** [test-kitchen/winrm-transport#2]
When using test-kitchen (with the winrm-transport), I often have failures in transferring all the files staged for transport.  A second converge usually makes things right.  It'd be nice to have a validate step on the remote end to make sure everything got there.

**Comment by usepowershell** [comment]
I have the debug logs from a Test-Kitchen run with a failed file transfer.  It looks like it was copied over to the staging, encoded location, but never made it to the "final" temp location.  

https://gist.github.com/smurawski/521957b68032e1c8aa99

**Comment by xmik** [comment]
I ran into failed file transfer too (`cookbooks` directory was never unzipped), [test-kitchen/test-kitchen/#642](https://github.com/test-kitchen/test-kitchen/issues/642) and posted [PR](https://github.com/test-kitchen/winrm-transport/pull/9) which resolved it for me on Windows 7.

**Comment by fnichol** [comment]
@smurawski is it possible that #8 resolves this?

**Comment by usepowershell** [comment]
Yep, closed via #8 and there are pester tests for that use case.
