### ISSUE TITLE
kitchen create error with winrm

### ISSUE THREAD

**Issue by davidmgrantham** [test-kitchen/winrm-transport#21]
-----> Starting Kitchen (v1.4.2)
!!!!!! The `winrm-transport' gem is missing and must be installed or cannot be properly activated. Run`gem install winrm-transport --version '~> 1.0'`or add the following to your Gemfile if you are using Bundler:`gem 'winrm-transport', '~> 1.0'`.

> > > > > > ------Exception-------
> > > > > > Class: Kitchen::UserError
> > > > > > ## Message: Could not load or activate WinRM::Transport (winrm-transport is not part of the bundle. Add it to Gemfile.)
> > > > > > 
> > > > > > Please see .kitchen/logs/kitchen.log for more details
> > > > > > Also try running `kitchen diagnose --all` for configuration

uuidtools (2.1.5)
web-console (2.2.1)
winrm (1.4.0)
winrm-transport (1.0.3)
wmi-lite (1.0.0)
xml-simple (1.1.5)

Please help. I have i tried uninstalling and reinstalling as well as install 1.0.2 with luck.

**Comment by usepowershell** [comment]
How are you running test-kitchen?  Via Bundler? Via ChefDK? Directly from gems installed on your system?

**Comment by usepowershell** [comment]
Ah, and I see winrm 1.4.0 - winrm-transport has a current dependency on 1.3.x of the winrm gem.

I'd try 
`gem install winrm -v 1.3.5`

and retry test-kitchen.

You might need to remove the 1.4 version of winrm.

**Comment by davidmgrantham** [comment]
ChefDK

**Comment by davidmgrantham** [comment]
uuidtools (2.1.5)
web-console (2.2.1)
winrm (1.3.0)
winrm-transport (1.0.3)
wmi-lite (1.0.0)
xml-simple (1.1.5)

Still not working..

**Comment by usepowershell** [comment]
What platform are you on?  How are you installing the gems?  `chef gem install`?

**Comment by davidmgrantham** [comment]
I'm running it on a mac. 

gem install ***

ruby 2.2.1p85

**Comment by usepowershell** [comment]
ChefDK includes it's own Ruby installation which is what test-kitchen will use.  You'll need to use `chef gem install winrm-transport` or use `chef shell-init` for the shell type you are using as described https://docs.chef.io/install_dk.html under Setting the System Ruby.

WIthout either of the above, you are likely installing the gems to a location that test-kitchen won't find.

**Comment by davidmgrantham** [comment]
Looks like running `chef shell-init bash` work for me. Thanks!

**Comment by usepowershell** [comment]
Awesome.  That'll set your current shell session to use the ChefDK ruby, without screwing up any permanent system settings.

Happy testing!
